[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[template]
  incoming-hooks = ["URL Submitted"]

 [template.environment]
  ROUTES_FORM_ID = "The ID of the form in your Netlify site which contains all of your active routes"
  API_AUTH = "Your personal Netlify API authentication token"